#apiVersion: v1
#kind: Service #type of resource
#metadata:
#  name: first-svc
#spec:
#  ports:
#    - port: 80 #port num of svc
#      protocol: TCP
#      targetPort: 80 #port num of container for svc connect
#  selector:
#    app: first-deoloyment #label of pod for svc connect
#
#
#    example service for deployment nodeport
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-svc-np
# spec:
#   type: NodePort
#   ports:
#   - port: 80 #port num of svc
#     targetPort: 80 #port num of container for svc connect
#     nodePort: 32000
#   selector:
#     app: nginx
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-lb
spec: 
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx

